[project]
name = "lab1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Artem Filuta", email = "artfilutah2007@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pandas>=3.0.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
app = "lab1.main:main"
